actors:
  sageszk:
    image_url: /images/actors/alice.png
    name: sageszk
    url: https://twitter.com/sageszk
author: sageszk
description: sageszkのpodcastです
description_long: sageszkのpodcastです
email: madanai
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: sageszk
itunes_podcast_url:
keywords: radio,hobby,anime,study
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: sageszkのなにかしら
url: https://sageszk.github.io/
